# Generated by Django 3.2.15 on 2022-09-01 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_featuredpost_trendingpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpost',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featuredPosts', to='product.product'),
        ),
        migrations.AlterField(
            model_name='trendingpost',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trendingPost', to='product.product'),
        ),
    ]
