# Generated by Django 4.0.4 on 2022-08-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_shippingaddress_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
