# Generated by Django 4.0.4 on 2022-09-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_headeroffer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headeroffer',
            name='image',
            field=models.ImageField(blank=True, height_field='1408', null=True, upload_to='header/main.jpg', width_field='993'),
        ),
    ]
