# Generated by Django 4.0.4 on 2022-09-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_headeroffer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='headeroffer',
            name='enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='headeroffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='header/'),
        ),
    ]
