# Generated by Django 4.0.4 on 2022-09-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_headeroffer_enable_alter_headeroffer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='headeroffer',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='header/'),
        ),
        migrations.AddField(
            model_name='headeroffer',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='header/'),
        ),
    ]
