# Generated by Django 4.0.4 on 2022-09-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_headeroffer_image_1_headeroffer_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headeroffer',
            name='main_line',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='headeroffer',
            name='offer_line',
            field=models.CharField(max_length=150),
        ),
    ]
